app:
  id: demo2
  # Mac/Linux: /opt/data/{appId}/config-cache
  # Windows: C:\opt\data\{appId}\config-cache
  # 缓存文件 : {appId}+{cluster}+{namespace}.properties
  # cacheDir: C:\\opt\\data\\${app.id}\\config-cache

apollo:
  bootstrap:
    enabled: true
    namespaces: application,TEST1.redis
# ---- 环境
# 对于Mac/Linux，文件位置为/opt/settings/server.properties
# 对于Windows，文件位置为C:\opt\settings\server.properties
# env=DEV

